/**
 * Build Twitter Experience Manager for dual console + userscript use.
 * Usage: node scripts/build.js
 *
 * Critical: the file MUST start with // ==UserScript== (no prefix) so
 * Violentmonkey / Tampermonkey can parse the metadata block.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = path.join(root, 'src');
const modulesDir = path.join(src, 'modules');

const HEADER = path.join(src, 'header.meta.js');
const BODY = [
  path.join(src, 'bootstrap.js'),
  path.join(modulesDir, 'core.js'),
  path.join(modulesDir, 'follow.js'),
  path.join(modulesDir, 'ui.js'),
  path.join(modulesDir, 'followers.js'),
  path.join(modulesDir, 'geoguard.js'),
  path.join(modulesDir, 'notifmute.js'),
  path.join(modulesDir, 'about.js'),
  path.join(src, 'boot.js'),
  path.join(src, 'footer.js'),
];

function read(p) {
  if (!fs.existsSync(p)) throw new Error('Missing: ' + p);
  // Strip UTF-8 BOM if present (PowerShell Set-Content often adds one)
  let t = fs.readFileSync(p, 'utf8');
  if (t.charCodeAt(0) === 0xfeff) t = t.slice(1);
  return t.replace(/\r\n/g, '\n');
}

let header = read(HEADER).trim();
// Ensure metadata is the first thing parsers see
if (!header.startsWith('// ==UserScript==')) {
  const idx = header.indexOf('// ==UserScript==');
  if (idx === -1) throw new Error('header.meta.js missing // ==UserScript== block');
  header = header.slice(idx);
}

const bodyParts = BODY.map((p) => {
  const rel = path.relative(root, p).replace(/\\/g, '/');
  return '\n/* ---- ' + rel + ' ---- */\n' + read(p).trimEnd() + '\n';
});

const banner =
  '\n/*\n' +
  ' * AUTO-GENERATED by scripts/build.js — edit src/ then rebuild.\n' +
  ' * Built: ' + new Date().toISOString() + '\n' +
  ' * Violentmonkey: @inject-into content (X.com CSP blocks page injection).\n' +
  ' */\n';

const out = header + '\n' + banner + bodyParts.join('') + '\n';

// Validate metadata is first non-empty line content
const firstLine = out.split('\n').find((l) => l.trim().length > 0);
if (!firstLine || !firstLine.includes('==UserScript==')) {
  throw new Error('Build sanity check failed: output does not start with UserScript metadata');
}

fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
const distPath = path.join(root, 'dist', 'twitter-experience-manager.user.js');
const rootPath = path.join(root, 'twitter-experience-manager.js');

// Write UTF-8 without BOM
fs.writeFileSync(distPath, out, { encoding: 'utf8' });
fs.writeFileSync(rootPath, out, { encoding: 'utf8' });

console.log('Built', distPath, '(' + out.length + ' bytes)');
console.log('First line:', firstLine);
console.log('inject-into:', (out.match(/@inject-into\s+(\S+)/) || [])[1] || '(none)');
