/**
 * Build Twitter Experience Manager for dual console + userscript use.
 * Usage: node scripts/build.js
 *
 * - Output MUST start with // ==UserScript==
 * - Strip UTF-8 BOM from every source part
 * - Prefer ASCII-safe packaging for Violentmonkey on X.com
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = path.join(root, 'src');
const modulesDir = path.join(src, 'modules');

const HEADER = path.join(src, 'header.meta.js');
const BODY = [
  path.join(src, 'bootstrap.js'),
  path.join(modulesDir, 'core.js'),
  path.join(modulesDir, 'follow.js'),
  path.join(modulesDir, 'ui.js'),
  path.join(modulesDir, 'followers.js'),
  path.join(modulesDir, 'geoguard.js'),
  path.join(modulesDir, 'notifmute.js'),
  path.join(modulesDir, 'about.js'),
  path.join(src, 'boot.js'),
  path.join(src, 'footer.js'),
];

function read(p) {
  if (!fs.existsSync(p)) throw new Error('Missing: ' + p);
  let buf = fs.readFileSync(p);
  // Strip UTF-8 BOM
  if (buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf) {
    buf = buf.slice(3);
  }
  let t = buf.toString('utf8');
  if (t.charCodeAt(0) === 0xfeff) t = t.slice(1);
  return t.replace(/\r\n/g, '\n');
}

let header = read(HEADER).trim();
const idx = header.indexOf('// ==UserScript==');
if (idx === -1) throw new Error('header.meta.js missing // ==UserScript== block');
header = header.slice(idx);

const bodyParts = BODY.map((p) => {
  const rel = path.relative(root, p).replace(/\\/g, '/');
  return '\n/* ---- ' + rel + ' ---- */\n' + read(p).trimEnd() + '\n';
});

const banner =
  '\n/*\n' +
  ' * AUTO-GENERATED by scripts/build.js - edit src/ then rebuild.\n' +
  ' * Built: ' + new Date().toISOString() + '\n' +
  ' * VM: @grant GM_info + @inject-into content (X.com CSP).\n' +
  ' */\n';

const out = header + '\n' + banner + bodyParts.join('') + '\n';

const firstLine = out.split('\n').find((l) => l.trim().length > 0);
if (!firstLine || firstLine.indexOf('==UserScript==') === -1) {
  throw new Error('Build sanity check failed: output does not start with UserScript metadata');
}

// Parse-check the JS body (strip metadata)
const code = out.replace(/\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/, '');
try {
  // eslint-disable-next-line no-new-func
  new Function(code);
} catch (e) {
  throw new Error('Built script does not parse: ' + e.message);
}

fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
const distPath = path.join(root, 'dist', 'twitter-experience-manager.user.js');
const rootPath = path.join(root, 'twitter-experience-manager.js');
const smokePath = path.join(root, 'dist', 'tem-smoke-test.user.js');

fs.writeFileSync(distPath, out, { encoding: 'utf8' });
fs.writeFileSync(rootPath, out, { encoding: 'utf8' });

// Tiny diagnostic userscript - if this fails, VM itself cannot inject on X
const smoke = `// ==UserScript==
// @name         TEM Smoke Test (X inject check)
// @namespace    https://github.com/HyperboreanSlug/Twitter-Experience-Manager
// @version      1.0.0
// @description  Minimal Violentmonkey inject test for x.com. If this fails, TEM cannot load either.
// @match        *://x.com/*
// @match        *://*.x.com/*
// @match        *://twitter.com/*
// @match        *://*.twitter.com/*
// @grant        GM_info
// @inject-into  content
// @run-at       document-end
// ==/UserScript==

(function () {
  'use strict';
  try {
    console.log('[TEM smoke] injected OK', typeof GM_info !== 'undefined' ? GM_info.script.name : 'no GM_info');
    var el = document.createElement('div');
    el.id = 'tem-smoke';
    el.textContent = 'TEM smoke test: Violentmonkey inject works on this page.';
    el.setAttribute('style',
      'position:fixed;bottom:12px;left:12px;z-index:2147483647;background:#0f1419;color:#e7e9ea;' +
      'border:1px solid #1d9bf0;border-radius:12px;padding:10px 14px;font:13px system-ui,sans-serif;' +
      'box-shadow:0 8px 24px rgba(0,0,0,.45)');
    (document.body || document.documentElement).appendChild(el);
    setTimeout(function () { try { el.remove(); } catch (e) {} }, 8000);
  } catch (err) {
    console.error('[TEM smoke] failed', err);
  }
})();
`;
fs.writeFileSync(smokePath, smoke, { encoding: 'utf8' });

console.log('Built', distPath, '(' + out.length + ' bytes)');
console.log('Smoke', smokePath);
console.log('First line:', firstLine);
console.log('grant:', (out.match(/@grant\s+(\S+)/) || [])[1]);
console.log('inject-into:', (out.match(/@inject-into\s+(\S+)/) || [])[1]);
console.log('parse: OK');
