/**
 * Build Twitter Experience Manager for dual console + Greasemonkey use.
 * Usage: node scripts/build.js
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = path.join(root, 'src');
const modulesDir = path.join(src, 'modules');

const ORDER = [
  path.join(src, 'header.meta.js'),
  path.join(src, 'bootstrap.js'),
  path.join(modulesDir, 'core.js'),
  path.join(modulesDir, 'follow.js'),
  path.join(modulesDir, 'ui.js'),
  path.join(modulesDir, 'followers.js'),
  path.join(modulesDir, 'geoguard.js'),
  path.join(modulesDir, 'notifmute.js'),
  path.join(modulesDir, 'about.js'),
  path.join(src, 'boot.js'),
  path.join(src, 'footer.js'),
];

function read(p) {
  if (!fs.existsSync(p)) throw new Error('Missing: ' + p);
  return fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n');
}

const parts = ORDER.map((p) => {
  const body = read(p).trimEnd();
  return '\n/* ---- ' + path.relative(root, p).replace(/\\/g, '/') + ' ---- */\n' + body + '\n';
});

const banner =
  '/*\n' +
  ' * AUTO-GENERATED by scripts/build.js — edit src/ then rebuild.\n' +
  ' * Built: ' + new Date().toISOString() + '\n' +
  ' */\n';

const out = parts[0].trimStart() + '\n' + banner + parts.slice(1).join('');
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
const distPath = path.join(root, 'dist', 'twitter-experience-manager.user.js');
const rootPath = path.join(root, 'twitter-experience-manager.js');
fs.writeFileSync(distPath, out);
fs.writeFileSync(rootPath, out);
console.log('Built', distPath, '(' + out.length + ' bytes)');
